#!/usr/bin/env bash
# LLM TeamWork — install nginx vhost for tm.9swt.com.
#
# Detects existing SSL certs on the host and writes /etc/nginx/conf.d/<DOMAIN>.conf
# accordingly. Falls back to plain HTTP if no cert is found, so the site is at
# least reachable; you can re-run later once a cert is in place.
#
# Run on the server as root:
#
#   curl -fsSL https://gitee.com/yhhj123/llmteamwork/raw/main/deploy/install-nginx.sh | bash
#
# Optional env vars:
#   DOMAIN          server_name (default tm.9swt.com)
#   APP_HOST_PORT   upstream port (default 3050)
#   SSL_CERT        explicit path to fullchain.pem (skip auto-detect)
#   SSL_KEY         explicit path to privkey.pem
#   FORCE_HTTP      =1 to skip TLS even if a cert is detected

set -euo pipefail

DOMAIN="${DOMAIN:-tm.9swt.com}"
APP_HOST_PORT="${APP_HOST_PORT:-3050}"
SSL_CERT="${SSL_CERT:-}"
SSL_KEY="${SSL_KEY:-}"
FORCE_HTTP="${FORCE_HTTP:-0}"
TARGET="/etc/nginx/conf.d/${DOMAIN}.conf"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!! \033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mxx \033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root (or via sudo)."
command -v nginx >/dev/null 2>&1 || die "nginx not found on PATH."
[ -d /etc/nginx/conf.d ] || die "/etc/nginx/conf.d not found."

# --- Locate cert + key -------------------------------------------------------
detect_cert() {
  # 1) explicit user-supplied paths win.
  if [ -n "$SSL_CERT" ] && [ -n "$SSL_KEY" ]; then
    [ -r "$SSL_CERT" ] && [ -r "$SSL_KEY" ] || die "SSL_CERT/SSL_KEY not readable."
    echo "$SSL_CERT|$SSL_KEY"; return 0
  fi
  # 2) certbot per-host
  local p="/etc/letsencrypt/live/${DOMAIN}"
  if [ -r "$p/fullchain.pem" ] && [ -r "$p/privkey.pem" ]; then
    echo "$p/fullchain.pem|$p/privkey.pem"; return 0
  fi
  # 3) certbot wildcard at the parent zone (e.g. *.9swt.com)
  local zone="${DOMAIN#*.}"
  for cand in "/etc/letsencrypt/live/${zone}" "/etc/letsencrypt/live/*.${zone}"; do
    for hit in $cand; do
      if [ -r "$hit/fullchain.pem" ] && [ -r "$hit/privkey.pem" ]; then
        echo "$hit/fullchain.pem|$hit/privkey.pem"; return 0
      fi
    done
  done
  # 4) any path mentioned by an existing 9swt vhost.
  if [ -d /etc/nginx/conf.d ]; then
    local existing
    existing=$(grep -hE 'ssl_certificate(_key)?\s+' /etc/nginx/conf.d/*.conf 2>/dev/null \
              | awk '{print $2}' | tr -d ';' | sort -u)
    local cert key
    cert=$(echo "$existing" | grep -E 'fullchain|\.crt|\.cer|\.pem' | grep -v 'privkey\|\.key' | head -1)
    key=$(echo "$existing"  | grep -E 'privkey|\.key' | head -1)
    if [ -n "$cert" ] && [ -n "$key" ] && [ -r "$cert" ] && [ -r "$key" ]; then
      echo "$cert|$key"; return 0
    fi
  fi
  return 1
}

USE_HTTPS=0
CERT="" KEY=""
if [ "$FORCE_HTTP" != "1" ]; then
  if detected=$(detect_cert); then
    CERT="${detected%|*}"
    KEY="${detected#*|}"
    USE_HTTPS=1
    log "TLS cert detected:"
    log "    cert: $CERT"
    log "    key : $KEY"
  else
    warn "No TLS cert detected; writing HTTP-only vhost."
    warn "Re-run with SSL_CERT=... SSL_KEY=... once a cert is available,"
    warn "or use certbot: certbot certonly --webroot -w /var/www/letsencrypt -d $DOMAIN"
  fi
fi

# --- Write vhost -------------------------------------------------------------
TMP=$(mktemp)
{
  cat <<EOF
# Auto-generated by deploy/install-nginx.sh
upstream llm_teamwork_upstream {
    server 127.0.0.1:${APP_HOST_PORT};
    keepalive 32;
}

EOF

  if [ "$USE_HTTPS" = "1" ]; then
    cat <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
    }
    location / { return 301 https://\$host\$request_uri; }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     ${CERT};
    ssl_certificate_key ${KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache   shared:SSL_TM:10m;
    ssl_session_timeout 1d;

    client_max_body_size 30m;
    proxy_read_timeout   60s;
    proxy_send_timeout   60s;

    location / {
        proxy_pass http://llm_teamwork_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host  \$host;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$http_connection;
    }

    location /api/mcp {
        proxy_pass http://llm_teamwork_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_buffering    off;
        add_header Cache-Control "no-store" always;
    }

    access_log /var/log/nginx/${DOMAIN}.access.log;
    error_log  /var/log/nginx/${DOMAIN}.error.log warn;
}
EOF
  else
    cat <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    client_max_body_size 30m;
    proxy_read_timeout   60s;

    location / {
        proxy_pass http://llm_teamwork_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host  \$host;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$http_connection;
    }

    access_log /var/log/nginx/${DOMAIN}.access.log;
    error_log  /var/log/nginx/${DOMAIN}.error.log warn;
}
EOF
  fi
} > "$TMP"

if [ -f "$TARGET" ] && cmp -s "$TMP" "$TARGET"; then
  log "$TARGET is already up-to-date; skipping write."
else
  if [ -f "$TARGET" ]; then
    cp -f "$TARGET" "${TARGET}.bak.$(date +%s)"
    log "Backed up existing config to ${TARGET}.bak.<ts>"
  fi
  install -m 0644 "$TMP" "$TARGET"
  log "Wrote $TARGET"
fi
rm -f "$TMP"

# --- Validate + reload -------------------------------------------------------
log "Running 'nginx -t'..."
nginx -t

log "Reloading nginx..."
systemctl reload nginx 2>/dev/null || nginx -s reload

# --- Verify upstream + end-to-end -------------------------------------------
log "Probing upstream at 127.0.0.1:${APP_HOST_PORT}..."
if ! curl -fsS --max-time 5 -o /dev/null "http://127.0.0.1:${APP_HOST_PORT}/"; then
  warn "Upstream not responding. Is the docker container running?"
  warn "  docker compose -f /opt/llm-teamwork/docker-compose.yml ps"
fi

log "Probing through nginx (Host: ${DOMAIN})..."
if [ "$USE_HTTPS" = "1" ]; then
  curl -sS -I --max-time 8 -H "Host: ${DOMAIN}" "https://127.0.0.1/" -k 2>&1 | head -5 || true
else
  curl -sS -I --max-time 8 -H "Host: ${DOMAIN}" "http://127.0.0.1/" 2>&1 | head -5 || true
fi

cat <<EOF

Done. Visit:
  $( [ "$USE_HTTPS" = "1" ] && echo "https://${DOMAIN}/" || echo "http://${DOMAIN}/")

Tail logs:
  tail -f /var/log/nginx/${DOMAIN}.access.log
  tail -f /var/log/nginx/${DOMAIN}.error.log
EOF
